### ISSUE TITLE
Can the code of Qatten reproduce the performance in the Qatten paper?

### ISSUE THREAD

**Issue by GoingMyWay** [simsimiSION/pymarl-algorithm-extension#1]
Hi, thank you for this repro. Did you reproduce the performance of Qatten?

**Comment by simsimiSION** [comment]
i am sorry to say that I haven not test all scenarios in SMAC.

**Comment by GoingMyWay** [comment]
> i am sorry to say that I haven not test all scenarios in SMAC.

Thank you, I also found the implementation of Qatten from this repro: https://github.com/wjh720/QPLEX/blob/master/pymarl-master/src/config/algs/qatten.yaml
